services:
  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    volumes:
      - static:/vol/static
      - media:/vol/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - static:/vol/static
    depends_on:
      - backend

  gateway:
    build:
      context: ./nginx
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - static:/vol/static
      - media:/vol/media
    depends_on:
      - backend
      - frontend

volumes:
  static:
  media:
  pg_data: